name: kdg

services:
  app_postgres:
    image: postgres:17.6-alpine
    restart: always
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'postgres'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5443:5432'
    networks:
      - kdg-backend
    volumes:
      - ./postgresql/data:/var/lib/postgresql
#      - ./init-scripts/sql:/docker-entrypoint-initdb.d

  app_rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
    ports:
      - "5672:5672" #AMQP
      - "15672:15672" #MGMT
    networks:
      - kdg-backend
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
  
  delivery_service:
    image: registry.gitlab.com/kdg-ti/programming6/material/2025-2026/delivery-service
    environment:
      SPRING_PROFILES_ACTIVE: 'docker'
      SPRING_RABBITMQ_HOST: 'app_rabbitmq'
    pull_policy: "always"
    ports:
      - "8095:8095"
    networks:
      - kdg-backend

  idp_mysql:
    image: mysql:9.0.1
    volumes:
      - ./idp_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'keycloak'
      MYSQL_USER: 'keycloak'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3307:3306'
    networks:
      - kdg-kc

  idp_keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
      KC_DB: 'mysql'
      KC_DB_URL_HOST: 'idp_mysql'
      KC_DB_URL_DATABASE: 'keycloak'
      KC_DB_USERNAME: 'keycloak'
      KC_DB_PASSWORD: 'password'
    command: start-dev
    ports:
      - "8180:8080"
    depends_on:
      - idp_mysql
    networks:
      - kdg-kc

networks:
  kdg-kc:
    name: kdg-kc-network
    driver: bridge
  kdg-backend:
    name: kdg-back-network
    driver: bridge

